eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.88:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
######################################## mysql conf ###########################################
spring:
  datasource:
    url: jdbc:mysql://192.168.1.88:3306/qs_db_admin_manager?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMutiQueries=true
    # driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

  zipkin:
    sender:
      type: rabbit
    #内存方式配置，不需要
    base-url: http://192.168.1.88：9411
    enabled: true

  rabbitmq:
    addresses: 192.168.1.88
    port: 5672
    username: root
    password: 123456
    virtual-host: /
  sleuth:
    sampler:
      probability: 1 #收集追踪信息的比率，如果是0.1则表示只记录10%的追踪数据，如果要全部追踪，设置为1（实际场景不推荐，因为会造成不小的性能消耗）


######################################## redis conf ###########################################
---
spring:
  redis:
    host: 192.168.1.88
    port: 6379
    timeout: 20000
    database: 0
    password:
    block-when-exhausted : true
    jedis:
      pool:
        max-idle: 200
        max-wait: 10000
  jackson:
    default-property-inclusion: non_null  #返回json对象值为null不显示

######################################## log conf ###########################################
#logging:
#  config: classpath:logback-spring.xml
######################################## ID 全局唯一key ###########################################
idgenerator:
  zkConStr: 192.168.1.88:2181
  parentNodePath: /id_generator_parent
  workerPathPrefix: /id_generator


# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 2000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list: 192.168.1.88:22122 #TrackerList参数,支持多个
  reqHost: 192.168.1.88
  fdfsStoragePort : 8888