server:
  port: 8068

  ######################################## mybatis conf ###########################################
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.qingshuo.growthservice.entity
    mapUnderscoreToCamelCase: true

#=====================================================================
ribbon:
    ReadTimeout: 600000
    SocketTimeout: 600000
    ConnectTimeout: 600000
    eureka:
      enabled: true
#===========================================feign
feign:
    hystrix:
      enabled: true
hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 300000
        circuitBreaker:
          sleepWindowInMilliseconds: 300000
          forceClosed: true




spring:
    servlet:
      multipart:
        enabled: true
        # 上传一个文件最大值,默认1Mb
        max-file-size: 10MB
        # 上传多个文件最大值,50Mb,默认10Mb
        max-request-size: 50MB
    profiles:
      active: dev
    application:
      name: growth_server



